//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace ResourceSystem
{
	public class ContainerBase : IPutTake, IActualSize, IStorage
	{
		double WeightLimit;
		double OwnWeight;
		double ContentWeight { get; }

		public ContainerBase ()
		{
		}
	}
}

