//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace ResourceSystem
{
    public abstract class ContainerBase : MonoBehaviour, IPutTake, IActualSize, IStorage
    {
        private double WeightLimit;
        private double OwnWeight;
        public abstract double ContentWeight { get; }

        public ContainerBase()
        {

        }

        public abstract double Put(Resource resource, double amount);
        public abstract double Take(Resource resource);
        public double VolumeLimit { get; set; }
        public double VolumeAvailable { get; set; }
        public abstract bool CanPut(Resource resource, double amount, out double acceptedAmount);
        public double Volume { get; set; }
        public double Weight { get; set; }
    }
}

