//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace ResourceSystem
{
	public class Container : ContainerBase
	{
		HashSet<ResourceDefinition> AcceptedTypes;
		List<Resource> resources;

		public Container ()
		{

		}
	}
}

