//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace ResourceSystem
{
	public class Container : ContainerBase
	{
		public HashSet<ResourceDefinition> AcceptedTypes;
		List<Resource> resources;
	    private readonly double _contentWeight;

	    public Container ()
		{

		}

	    public override double ContentWeight
	    {
	        get { return _contentWeight; }
	    }

	    public override double Put(Resource resource, double amount)
	    {
	        throw new NotImplementedException();
	    }

	    public override double Take(Resource resource)
	    {
	        throw new NotImplementedException();
	    }

	    public override bool CanPut(Resource resource, double amount, out double acceptedAmount)
	    {
	        throw new NotImplementedException();
	    }
	}
}

